name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Adjust the Java version as needed
        distribution: 'adopt'  # Specify the desired Java distribution (e.g., adopt, temurin)

    - name: Validate Gradle wrapper
      run: chmod +x ./gradlew && ./gradlew wrapper --gradle-version 7.2
      working-directory: ./  # Adjust the path to your project directory if necessary

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./  # Adjust the path to your project directory if necessary

